[tool.poetry]
name = "state-search-be"
version = "0.1.0"
description = ""
authors = ["timechess <tyc221@ruc.edu.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
prisma = "^0.15.0"
sentence-transformers = "^3.3.1"
grpcio = "^1.68.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
