version: "3.8"
services:
  # backend:
  #   build: ../lean-learn-be
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql://postgres:vgASaJGlnZ6uZ9VNAJtat0CSczn2v0NAKHDYPrOtZWaD5XFbos8cc72cTj6s@db:5432/test
  #   ports:
  #     - 80:3000
  # frontend:
  #   image: lean-state-search:latest
  #   depends_on:
  #     - pg
  #   network_mode: "host"
  pg:
    container_name: state-search-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vgASaJGlnZ6uZ9VNAJtat0CSczn2v0NAKHDYPrOtZWaD5XFbos8cc72cTj6s
    # ports:
    #   - 5432:5432
    network_mode: "host"
    volumes:
      - ~/.docker/.persist/state-search/pg-data:/var/lib/postgresql/data
